#!/usr/bin/env python

import os, sys
import shutil

args = sys.argv

jpg_file = args[1]
canon_raw = os.path.splitext(jpg_file)[0] + '.CR2'
fuji_raw = os.path.splitext(jpg_file)[0] + '.RAF'

# dir for selected files
sel_dir = os.path.join(os.path.dirname(jpg_file), 'selected')

if not os.path.exists(sel_dir):
    os.makedirs(sel_dir)

# copy files
shutil.copy2(jpg_file, sel_dir)

# if corresponding raw files exist, copy them too
if os.path.exists(canon_raw):
    shutil.copy2(canon_raw, sel_dir)

if os.path.exists(fuji_raw):
    shutil.copy2(fuji_raw, sel_dir)

sys.exit()
