#!/usr/bin/env python

"""
Rate current image with 5 stars
this is done by appending _#5stars to the filename
"""

import os, sys

args = sys.argv
filename = args[1]
basename, ext = os.path.splitext(filename)
new_filename = basename + '_#5stars' + ext

os.rename(filename, new_filename)


