#!/usr/bin/env python

import sys, os
from PIL import Image 


MAX_WIDTH = 1200
MAX_HEIGHT = 1200

args = sys.argv

if len(args) == 1:
    print 'Please specify filename'
    sys.exit()

orig_file = args[1]
filename, ext = os.path.splitext(orig_file)
smaller_file = filename + '_small' + ext

im = Image.open(orig_file)
im.thumbnail((MAX_WIDTH, MAX_HEIGHT))
im.save(smaller_file)

sys.exit()
